spring:
  application:
   name: api-gateway-service

  cloud:
    gateway:
       routes:
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/v1/bookings/**
          filters:
            - AddRequestHeader=X-Request-Id, Rohan
            - StripPrefix=2
        - id: flight-service
          uri: lb://FLIGHT-SERVICE
          predicates:
            - Path=/api/v1/flights/**
          filters:
            - AddRequestHeader=X-Request-Id, Rohan
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka